#!/usr/bin/env perl

# vim: ft=perl

use strict;
use warnings;

package myworld {
    use base 'Games::Roguelike::World';
}

package main;

# creates a world with specified width/height & map display width/height
my $world
  = myworld->new( w => 80, h => 50, dispw => 40, disph => 18, debug => 1 );

# create a new area in this world called "1"
$world->area( Games::Roguelike::Area::Cavelike->new( name => '1' ) );

# make a cavelike maze
$world->area->generate();

# add a mobile object with symbol '@'
my $char = Games::Roguelike::Mob->new( $world->area, sym => '@', pov => 8 );

# set viewpoint to be from $char's perspective
$world->setvp($char);

# draw the active area map from the current perspective
$world->drawmap();

# move until 'q'
while ( !( ( my $c = $world->getch() ) eq 'q' ) ) {
    $char->kbdmove($c);
    $world->drawmap();
}

__END__

=head1 NAME

synop - Generates a random cavelike maze and lets you "walk" through it

=head1 SYNOPSIS

  $ perl scripts/synop
