#!/usr/bin/env perl

# vim: ft=perl

use strict;
use warnings;

package myworld;
use base 'Games::Roguelike::World';

# creates a world with specified width/height & map display width/height
my $r = myworld->new( w => 80, h => 50, dispw => 40, disph => 18 );

# create a new area in this world called "1"
$r->area( Games::Roguelike::Area->new( name => '1' ) );

# make a cavelike maze
$r->area->genmaze2();

# add a mobile object with symbol '@'
my $char = Games::Roguelike::Mob->new( $r->area, sym => '@', pov => 8 );

# set viewpoint to be from $char's perspective
$r->setvp($char);

# draw the active area map from the current perspective
$r->drawmap();

# move until 'q'
while ( !( ( my $c = $r->getch() ) eq 'q' ) ) {
    $char->kbdmove($c);
    $r->drawmap();
}

__END__

=head1 NAME

synop - Generates a random cavelike maze and lets you "walk" through it

=head1 SYNOPSIS

  $ perl scripts/synop
